spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://132.232.5.53:3306/z_admin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: Jy@375897
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
# 日志配置
logging:
  level:
    com.z: debug
    org.springframework: info
# mybatis
mybatis:
  type-aliases-package: com.z.admin.model
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    cache-enabled: false
server:
  port: 8080
  servlet:
    context-path: /admin
